# Stage:1
FROM python:3.9-slim AS build
WORKDIR /appy
COPY appy.py appy.py
RUN pip install flask && apt update && apt install -y build-essential


#Stage:2 Final/Production
FROM python:3.9-slim
WORKDIR /app
COPY --from=build /appy .
RUN pip install flask
EXPOSE 5000
ENTRYPOINT ["python"]
CMD ["appy.py"]

